name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install misspell
      run: go install github.com/client9/misspell/cmd/misspell

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck

    - name: Run misspell
      run: misspell cmd/**/*.{go,sh} internal/**/* README.md

    - name: Run go vet
      run: go vet -all ./...

    - name: Run go test
      run: go test -v -race ./...

    - name: Run staticcheck
      run: staticcheck ./... 

